language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: brainstorming-nodejs
  api_key:
    secure: Dj+2/iOQoKBzFBfLCBEj1TIYzKw6ycJibYiHx+q0mgcx9YNQ4JutfstycHL/AdI0QTlNkHTMiUp2tF74h3tIt81IxGKWSEEHU6FjKmyj/DKmLd8hmoVDmrlIWcY2FBdtR94PnSC2YQpjZw+/mFXC6md+3TzoS8k9Fg0zQIQFJJ5k0COvKSSG5OHiRwZYJbcoLKXykHdSOl8TljzUUEl0gro9UmXZyP1P6tg1wig1trWU3FjQo0etDuFP1QmtDCIOTqmG8V0NyzebFtRlyj4mtA88ijchHyt1b1vRxE3nfwFanCR+l4qSluRCkdMR4CSgJDcJYKWo4SaUYVLE/a4EbizXAtkqyiErryjumhn3r01asq0eWP1RL2gBmaSWy9QOySxx8OMf2qJAcuOyjSPsvflZUWUiJ/PqaefKX3+Unbm8R9J4s993Dc7Kp6VTYwI9IJrP+XGPSKacpy6HdidZe2oyalqI8vWlHEcxDmO4fgTsHej6cv0UsTgxLCgq3Haj7p0Q/an/Fd+pqOmMNr6+57c1BPxziYHamRFw8Nv7+VBRuxQnGtZqGR7cIEKq/CAhMYBgqrLvs496kFTHSpjo3PX7Bd9PNMXixWHt6j7ocCHjAgstpOXsNWH8xoynkjJS/9iS0Rzl2X15dxMk6NXWbUMjGuYgcnZMtjiRi53EAGQ=
