language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: brainstorming-nodejs
  api_key:
    secure: UmHzmZg+LTFGRkS3wrnUfmxllj60aVpkOhYHZmPTHOibc+aRl/z9PI80GvTJyS3nN3AqiT9Ioc3GZf2GtSRYUTsejRhx8HltXqRdShAh35qzo3DkMeNGYpGlujEWhstfq+Y1QDefLgqyYU9sGz6h0n7n/gz8a8USIf+pR5v5NUb6Yp0XNXu/0c3LRiCd+2HRBUYJq9p80JlbQ025fqegSf6ei66MgL+6jd7Dk24u3om24R/HXhk81UR8Nd4Ydxi9SAqsZCgF9RfSKkFXbpAZt6iaCKcdk16n8EOuQn5wDVYWqbA7TGNsEcypIF+mvnpOdxvPcQCkA6SVRzuKIYEooYV/hc+72PVAFPatFeO8UXzUBy+UARirohms+/FbxejVHwen1wbhS7/so2eO70KB0OTA0KQHMTalqUhmbujQh7y6FR4hSFD8ZcBPtv5CCwkkuzbmAVuxmP5/inZ+jqvMwaNnhZVrQtcZkvfv8Cuh25b9K4zjTUGAXdDn7GLBjR07nHBNYy8QSNzOdHHBDFyX66O0+zXPbJznpVKE8dBDi3tDcdHfzV07NUH2PvO0irDHcYKtLRqq4ldioY2qFCZtOPFcgjnh/ljIsDEs7BVg8a8dluZupfNN9KnZ+F/r/MOyBFWSaZZFryj6kT+JeWXobeZABtlLlJycquqURaKn8/Y=
