language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: brainstorming-nodejs
  api_key:
    secure: SYVXarEv/x8E5occQaMklQhDCor1cpvFy9xbmbFAgxMGJ5p01pc3w78bo7TPetA+njqAXUhTHQpyasb5ykLlqBsGb/sicR6DwuHlq1WM6nHYb1ASHhj+Q8kVmfumAePsgBnk92NTqGRerxqRmryGC2fv/4ofa1Yi9/OTMO7S5TYn/d0MgxQIZdgRsAPLXn1o2D4EKt7wE8i/s41g6AyFMH6ryU6u78n8P2vofsxuoDLh9RXlmfRWTxS2CIOBZ4EiM9ZHc2G9XeNLvkQ9eNaLw9mx0oBhzcsgJ/9GLVmfiO4U/Hlz3dbXAao60udz7Ot8t2Bzgi8AOv+OdlJALj7BZQp6KVNSVtStFWTw/0HEnC+kM+J4rNKea5qECI4DiEnl973DJFmhQHjmgJxgdZsDZQFgM8Icy2ezIdZheBM6a8S3ptBDBOSPGh84Xvx5V73fEfzQ3WtCFQjJsY9b9nOEZMsfD0BINMZ69NsgRDzol307JKW9AF0ZR8expGG1db05ROu6Vw7lbTNaWi8d7eH0vv+hrLLOhcEOD/BGV/BhFBKWwhjdYIkFlXomyAE+6FLnEPldWeQlATCSKRIFohKSc6N5aLygieUz05er4TNWRN2T9RoUcSd2BdXEgdlrN8rIsT3fQ6JhGDFPfXsQZoJ2oc1EBq0S4Mkh5cC6RPSoSlM=
