language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: brainstorming-nodejs
  api_key:
    secure: HrB+Glc9lZ2uFSzbt8BeFBdgLDwINDLyjndWtph7EUB+im+hdAs2kY9dbtbLKMLikC/Ffpbgl11f5p0hsDy7o3EJcnD6AbMLYH+266JlgkEB7bIxr6JvDu/iwXLfSRTGjQXfJDg40qV5qU65wUDr2DIH6ZEsRtOYJK7QkyW0TJciZTIewJfVNd1ezO2RBxZIUoF1pBT4jlBszH9Kenvj4w3D4A/fV5lX+OLAhXGglXmV8lviXhQrlnn8XWe6pK/EvgUSnLtqRdx5pEq3DpI5mGYIOo3TmIJ0a2zEzhYXz6StLF1a/qz5dNyvzgseKzJvc5IrW3WxETRYMNmGrqS+B61CBGML80xQWEap7ETIe3bYywrEOHf12pCn7HByzbCZ8gF1hD9a26n6A+XeOiPeBIpI7AgzVrmjZl50cYC0ytpvrfDVy+XzLuFpjd4/0Ne20zEpZivEbXtNJt0apYicVcJBYXHnZcxV/A4mYfEon4R0da3tG5ShLCQ0iWUiuAYIlkBrIRLXFT8745ysLfK0bX1xGj4M74/AvCXeiQWvm0SDf+OL7r60xAYgA1MRFAg+XHB220V7ksiWD55UsRfhdFZXsRrk3zEXHaKr+7ijdRRBi2oDVg9yjGpOxXuAxTohj4e4W2odsV+2sZvEMX/Pqlp+bSG0caK9reyb77NBcuM=
